-- Création des tables pour la base de données HSQLDB

-- Table des utilisateurs
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    profile_picture VARCHAR(255),
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Table des équipes
CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    logo VARCHAR(255),
    category VARCHAR(255) NOT NULL,
    coach_id BIGINT NOT NULL,
    FOREIGN KEY (coach_id) REFERENCES users(id)
);

-- Table des joueurs
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    license_number VARCHAR(255) NOT NULL UNIQUE,
    date_of_birth DATE NOT NULL,
    profile_picture VARCHAR(255),
    team_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (team_id) REFERENCES teams(id)
);

-- Table des compétitions
CREATE TABLE competitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    registration_deadline DATE,
    location VARCHAR(255) NOT NULL,
    max_teams INTEGER,
    competition_type VARCHAR(50) NOT NULL,
    competition_status VARCHAR(50) NOT NULL,
    organizer_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (organizer_id) REFERENCES users(id)
);

-- Table d'association entre compétitions et équipes
CREATE TABLE competition_teams (
    competition_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    PRIMARY KEY (competition_id, team_id),
    FOREIGN KEY (competition_id) REFERENCES competitions(id),
    FOREIGN KEY (team_id) REFERENCES teams(id)
);

-- Table des matchs
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id BIGINT NOT NULL,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    match_date TIMESTAMP NOT NULL,
    location VARCHAR(255),
    home_score INTEGER,
    away_score INTEGER,
    match_status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (competition_id) REFERENCES competitions(id),
    FOREIGN KEY (home_team_id) REFERENCES teams(id),
    FOREIGN KEY (away_team_id) REFERENCES teams(id)
);

-- Table des feuilles de match
CREATE TABLE match_sheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL UNIQUE,
    is_validated BOOLEAN,
    validation_date TIMESTAMP,
    strategy VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (match_id) REFERENCES matches(id)
);

-- Table des participations des joueurs aux matchs
CREATE TABLE player_participations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_sheet_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    shirt_number INTEGER,
    player_status VARCHAR(50) NOT NULL,
    position VARCHAR(255),
    goals_scored INTEGER,
    yellow_cards INTEGER,
    red_cards INTEGER,
    minutes_played INTEGER,
    substitution_in_time INTEGER,
    substitution_out_time INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (match_sheet_id) REFERENCES match_sheets(id),
    FOREIGN KEY (player_id) REFERENCES players(id)
);

-- Table des notifications
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    is_read BOOLEAN,
    notification_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Table des médias
CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    competition_id BIGINT,
    match_id BIGINT,
    uploaded_by BIGINT NOT NULL,
    created_at TIMESTAMP,
    FOREIGN KEY (competition_id) REFERENCES competitions(id),
    FOREIGN KEY (match_id) REFERENCES matches(id),
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

-- Table des classements
CREATE TABLE standings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    matches_played INTEGER,
    matches_won INTEGER,
    matches_drawn INTEGER,
    matches_lost INTEGER,
    goals_for INTEGER,
    goals_against INTEGER,
    goal_difference INTEGER,
    points INTEGER,
    rank INTEGER,
    updated_at TIMESTAMP,
    FOREIGN KEY (competition_id) REFERENCES competitions(id),
    FOREIGN KEY (team_id) REFERENCES teams(id)
);
